version: "3.4"
services:
  db:
    image: postgres:11.2-alpine
    container_name: lava-server-db
    environment:
      POSTGRES_USER: lavaserver
      POSTGRES_PASSWORD: lavaserverdbpass
    volumes:
    - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  lava-logs:
    container_name: lava-logs
    image: lavasoftware/lava-server:2019.03
    volumes:
    - joboutput:/var/lib/lava-server/default/media/job-output
    - ./overlays/lava-server/etc/lava-server/instance.conf:/etc/lava-server/instance.conf:ro
    - ./overlays/lava-server/etc/lava-server/settings.conf:/etc/lava-server/settings.conf:ro
    - ./overlays/lava-server/etc/lava-server/lava-logs:/etc/lava-server/lava-logs:ro
    depends_on:
    - db
    environment:
      SERVICES: "lava-logs"
    ports:
    - 5555:5555
    restart: unless-stopped
    stop_grace_period: 20s

  lava-master:
    container_name: lava-master
    #image: lavasoftware/lava-server:2019.03
    build:
      context: ./lite-lava-master
    cap_add:
    - SYS_ADMIN
    volumes:
    - devices:/etc/lava-server/dispatcher-config/devices:ro
    - health-checks:/etc/lava-server/dispatcher-config/health-checks:ro
    - ./overlays/lava-server/etc/lava-server/instance.conf:/etc/lava-server/instance.conf:ro
    - ./overlays/lava-server/etc/lava-server/settings.conf:/etc/lava-server/settings.conf:ro
    - ./overlays/lava-server/etc/lava-server/lava-master:/etc/lava-server/lava-master:ro
    depends_on:
    - db
    environment:
      SERVICES: "lava-master"
    ports:
    - 5556:5556
    restart: unless-stopped

  lava-publisher:
    container_name: lava-publisher
    image: lavasoftware/lava-server:2019.03
    volumes:
    - ./overlays/lava-server/etc/lava-server/instance.conf:/etc/lava-server/instance.conf:ro
    - ./overlays/lava-publisher/etc/lava-server/settings.conf:/etc/lava-server/settings.conf:ro
    environment:
      SERVICES: "lava-publisher"
    ports:
    - 5500:5500
    restart: unless-stopped

  lava-server:
    container_name: lava-server
    image: lavasoftware/lava-server:2019.03
    volumes:
    - devices:/etc/lava-server/dispatcher-config/devices
    - health-checks:/etc/lava-server/dispatcher-config/health-checks
    - joboutput:/var/lib/lava-server/default/media/job-output
    - ./overlays/lava-server/etc/lava-server/instance.conf:/etc/lava-server/instance.conf:ro
    - ./overlays/lava-server/etc/lava-server/settings.conf:/etc/lava-server/settings.conf:ro
    depends_on:
    - db
    environment:
      SERVICES: "gunicorn"
      BIND: "--bind lava-server:8000"
    restart: unless-stopped

  apache2:
    container_name: apache2
    image: lavasoftware/lava-server:2019.03
    volumes:
    - ./overlays/lava-server/etc/apache2/sites-available/lava-server.conf:/etc/apache2/sites-available/lava-server.conf:ro
    depends_on:
    - lava-server
    environment:
      SERVICES: "apache2"
    ports:
    - 80:80
    restart: unless-stopped

  lava-dispatcher:
    container_name: lava-dispatcher
    image: lavasoftware/lava-dispatcher:2019.03
    devices:
            #    - /dev/kvm # needed for QEMU
    - /dev/net/tun # needed for QEMU
    cap_add:
    - NET_ADMIN # needed for QEMU
    environment:
      DISPATCHER_HOSTNAME: "--hostname=lava-dispatcher"
      LOGGER_URL: "tcp://lava-logs:5555"
      MASTER_URL: "tcp://lava-master:5556"
    volumes:
    - /boot:/boot:ro
    - /lib/modules:/lib/modules:ro

volumes:
  db-data:
    name: lava-server-pgdata
  devices:
    name: lava-server-devices
  health-checks:
    name: lava-server-health-checks
  joboutput:
    name: lava-server-joboutput
