#!/usr/bin/python3

#  Copyright 2019 Linaro Limited
#  Author: Dave Pigott <dave.pigott@linaro.org>

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#  USB device passthrough for docker containers

import pyudev
import argparse
import os
import stat
import docker

def dev_info_from_device(device):
    dev_type = None
    mode = os.stat(device.device_node).st_mode
    if (stat.S_ISCHR(mode)):
        dev_type = "c"
    if (stat.S_ISBLK(mode)):
        dev_type = "b"

    return (dev_type, os.major(device.device_number), os.minor(device.device_number), device.device_node)

def get_device_numbers(serial_no):
    result = []
    context = pyudev.Context()

    devices = context.list_devices(subsystem='usb')
    device = None

    for device in devices:
        serial = device.attributes.get("serial")
        if serial is not None and serial_no in serial.decode("utf-8"):
            result.append(dev_info_from_device(device))
            break

    child = device.children
    for c in child:
        if c.device_number != 0 and c.subsystem in ["block", "tty"]:
            result.append(dev_info_from_device(c))

    return result


def pass_device_into_container(instance, devs):
    client = docker.from_env()

    container = client.containers.get(instance)

    for (dev_type, major, minor, node) in devs:
        allow_devices = open("/sys/fs/cgroup/devices/docker/%s/devices.allow" % container.id, "w")
        allow_devices.write("%s %s:%s rwm\n" % (dev_type, major, minor))
        allow_devices.close()
        create_dev_cmd = "sh -c '[ ! -e " + node + " ] " + \
                         "&& mkdir -p $(dirname " + node + \
                         ") && mknod " + node + " " + dev_type + \
                         " " + str(major) + " " + str(minor) + "'"
        container.exec_run(create_dev_cmd)

def main():
    parser = argparse.ArgumentParser(description='USB device passthrough for docker containers', add_help=False)

    parser.add_argument("-d", "--device_serial", type=str, required=True,
                        help="Devices serial number")
    parser.add_argument("-i", "--instance", type=str, required=True,
                        help="Docker instance")

    options = parser.parse_args()

    devs = get_device_numbers(options.device_serial)

    if devs is not None:
        pass_device_into_container(options.instance, devs)


if __name__ == '__main__':
    main()
